### ISSUE TITLE
Auto split array values

### ISSUE THREAD

**Issue by aurium** [sdumetz/node-xdg-parse#10]
String fields may have multiple values, separated by `;`. That is usual in `MimeType` key. When an (non scaped) `;` is found, the string must be splited.

**Comment by sdumetz** [comment]
When I wrote this I could not find something in the spec to specify whether or not it should always be done or left at the user's discretion. Are you sure this would not break some use cases and/or this is expected behavior from the specification?

Additionally, please edit the tests if you can so that they reflect the new behavior.
